FROM python:3.11-slim
WORKDIR /app
COPY ./frontend /app
RUN pip install --no-cache-dir -r requirements.txt
CMD ["streamlit", "run", "streamlit_app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
